import { Link } from 'react-router-dom';
import {
  ArrowRight,
  Sticker,
  Laptop,
  Music2,
  Bike,
  Backpack,
  Camera,
  Printer,
  Package,
  Sparkles,
  Radio,
} from 'lucide-react';
import { Container } from '@/components/ui/Container';
import { Eyebrow, Lede } from '@/components/brand/Typography';
import { cn } from '@/lib/cn';

const stickerUseCases = [
  {
    icon: Laptop,
    title: 'Laptops + monitors',
    body: 'A small round sticker on the lid. Disappears into the design; comes to life when scanned.',
  },
  {
    icon: Music2,
    title: 'Instruments + cases',
    body: 'Iron-on for fabric cases, vinyl for hard cases. Survives band practice. Survives baggage carousels.',
  },
  {
    icon: Backpack,
    title: "Kids' gear",
    body: 'Iron-on labels for uniforms and water bottles. Bulk packs sized for the season.',
  },
  {
    icon: Bike,
    title: 'Bikes + helmets',
    body: 'Weatherproof vinyl that survives a year of rain. Helmet liners, frame tubes, saddle rails.',
  },
  {
    icon: Camera,
    title: 'Cameras + lenses',
    body: 'Small enough to slot beside the serial sticker, big enough to scan in airport security.',
  },
  {
    icon: Radio,
    title: 'Headphones, AirPods, gear',
    body: 'The smallest case in our lineup. One inside every charging case, every Bose, every dongle.',
  },
];

const tiers = [
  {
    key: 'stickers',
    eyebrow: 'Stickers + labels',
    name: 'For laptops and the thousand things you forget about.',
    pricing: '$4 single · $18 5-pack · $36 12-pack · $99 40-pack',
    materials: 'Weatherproof vinyl, kiss-cut. Iron-on cotton labels for fabric.',
    description:
      'The lowest-friction QurTag. Stick it on the laptop lid, the camera body, the AirPods case, the kids\' clarinet. Buy a pack and you tag the whole household in an afternoon.',
    featured: true,
  },
  {
    key: 'printable',
    eyebrow: 'Printable',
    name: 'A4 PDF you cut out and tape.',
    pricing: 'Free with any plan',
    materials: 'Whatever paper you have. Laminated lasts longer.',
    description:
      'The cheapest way to try QurTag. Generated by the app the moment you create your first item.',
    featured: false,
  },
  {
    key: 'core',
    eyebrow: 'Core',
    name: 'Soft-touch silicone in matte black.',
    pricing: '$14 single · $26 2-pack',
    materials: 'Premium silicone with stainless cable. TSA-friendly.',
    description:
      "The everyday luggage tag. Survives baggage handlers and the rain. Looks at home on an Away carry-on.",
    featured: false,
  },
  {
    key: 'pro',
    eyebrow: 'Pro',
    name: 'Anodized aluminum, laser-etched.',
    pricing: '$28 single · $52 2-pack',
    materials: 'Aerospace-grade aluminum with brushed finish. NFC chip embedded.',
    description:
      'The everyday tag for the people who fly weekly. Quiet, premium, opens with a tap on any modern phone.',
    featured: false,
  },
  {
    key: 'signature',
    eyebrow: 'Signature',
    name: 'Full-grain leather with brass hardware.',
    pricing: '$58 · monogrammed',
    materials: 'Vegetable-tanned leather, brass D-ring, hand-finished. Ships in 5 days with engraving.',
    description:
      'The gift-grade QurTag. Looks like Bellroy, behaves like QurTag. Carry it on a Rimowa and nobody asks what it is, but they do ask where you got it.',
    featured: false,
  },
  {
    key: 'track',
    eyebrow: 'Track',
    name: 'Aluminum + Bluetooth beacon.',
    pricing: '$72 · subscription-free',
    materials: 'Aluminum body with replaceable coin cell. Apple Find My + Google Find Hub compatible.',
    description:
      'The premium hybrid. Pings from inside the Find My / Find Hub networks at no extra cost, and falls back to the QurTag recovery loop when out of range.',
    featured: false,
  },
];

export function Tags() {
  return (
    <>
      {/* Hero */}
      <section>
        <Container size="xl">
          <div className="pt-cairn-8 pb-cairn-8 md:pt-16 md:pb-cairn-8 max-w-3xl flex flex-col gap-5">
            <Eyebrow>The hardware</Eyebrow>
            <h1 className="font-display font-semibold text-ink-900 text-h2 sm:text-h1 tracking-[-0.035em] leading-[0.95] text-balance">
              From a $4 sticker to hand-stitched leather.
            </h1>
            <Lede>
              QurTag works the same on every form factor. Pick whichever fits the thing you're
              tagging. A sticker on the laptop, a leather tag on the suitcase, paper inside the
              kid's clarinet case. The software is identical underneath.
            </Lede>
          </div>
        </Container>
      </section>

      {/* Stickers hero band */}
      <section className="border-t border-hairline bg-paper">
        <Container size="xl">
          <div className="py-cairn-12 md:py-cairn-8 grid lg:grid-cols-12 gap-cairn-8 items-start">
            <div className="lg:col-span-5 flex flex-col gap-4 lg:sticky lg:top-28">
              <div className="size-12 rounded-pill bg-signal-500 grid place-items-center">
                <Sticker size={22} strokeWidth={1.5} className="text-canvas" />
              </div>
              <Eyebrow>Stickers + labels</Eyebrow>
              <h2 className="font-display font-semibold text-ink-900 text-h2 sm:text-h1 tracking-[-0.032em] leading-[1.02] text-balance">
                For the thousand things you'd rather not lose.
              </h2>
              <Lede className="max-w-md">
                Weatherproof vinyl. Iron-on for cotton. Small enough to disappear, big enough to
                scan. The QurTag tier most households actually need.
              </Lede>
              <div className="flex items-center gap-6 mt-2">
                <Link
                  to="/start"
                  className="inline-flex h-12 items-center gap-2 rounded-pill bg-ink-900 px-6 text-body font-medium text-canvas hover:bg-ink-700 transition-colors duration-cairn"
                >
                  Get a pack. From $18
                  <ArrowRight size={16} strokeWidth={1.75} />
                </Link>
              </div>
            </div>
            <div className="lg:col-span-7 grid sm:grid-cols-2 gap-3">
              {stickerUseCases.map((u) => (
                <article
                  key={u.title}
                  className="rounded-modal border border-hairline bg-canvas p-cairn-5 flex flex-col gap-3 hover:border-hairline-strong transition-colors duration-cairn"
                >
                  <u.icon size={22} strokeWidth={1.25} className="text-verdigris-700" />
                  <h3 className="font-display font-semibold text-h5 text-ink-900 tracking-[-0.018em] text-balance">
                    {u.title}
                  </h3>
                  <p className="text-caption text-muted text-pretty">{u.body}</p>
                </article>
              ))}
            </div>
          </div>
        </Container>
      </section>

      {/* All tiers */}
      <section className="border-t border-hairline">
        <Container size="xl">
          <div className="py-cairn-12 md:py-cairn-8 flex flex-col gap-cairn-8">
            <div className="max-w-3xl flex flex-col gap-4">
              <Eyebrow>The full lineup</Eyebrow>
              <h2 className="font-display font-semibold text-ink-900 text-h2 sm:text-h1 tracking-[-0.032em] leading-[1.02] text-balance">
                Six tiers. One calm app behind all of them.
              </h2>
            </div>
            <div className="flex flex-col gap-3">
              {tiers.map((tier, idx) => (
                <article
                  key={tier.key}
                  className={cn(
                    'rounded-modal border p-cairn-5 grid md:grid-cols-12 gap-cairn-3 items-start',
                    'transition-all duration-cairn',
                    tier.featured
                      ? 'border-signal-200 bg-signal-50'
                      : 'border-hairline bg-canvas hover:border-hairline-strong',
                  )}
                >
                  <div className="md:col-span-1 flex md:flex-col items-center md:items-start gap-3">
                    <span className="font-mono text-caption text-muted">
                      {String(idx + 1).padStart(2, '0')}
                    </span>
                  </div>
                  <div className="md:col-span-5 flex flex-col gap-2">
                    <Eyebrow>{tier.eyebrow}</Eyebrow>
                    <h3 className="font-display font-semibold text-h4 text-ink-900 tracking-[-0.018em] text-balance">
                      {tier.name}
                    </h3>
                    <p className="text-caption text-muted">{tier.materials}</p>
                  </div>
                  <div className="md:col-span-4 flex flex-col gap-2">
                    <p className="text-body text-ink-700 text-pretty">{tier.description}</p>
                  </div>
                  <div className="md:col-span-2 flex flex-col gap-2 items-start md:items-end md:text-right">
                    <span className="text-caption text-muted">From</span>
                    <span className="text-body font-medium text-ink-900">{tier.pricing}</span>
                  </div>
                </article>
              ))}
            </div>
          </div>
        </Container>
      </section>

      {/* "Bring your own QR" */}
      <section className="border-t border-hairline bg-paper">
        <Container size="md">
          <div className="py-cairn-8 flex flex-col items-start gap-4">
            <div className="size-10 rounded-pill bg-ink-50 grid place-items-center">
              <Sparkles size={18} strokeWidth={1.5} className="text-ink-900" />
            </div>
            <Eyebrow>Or bring your own</Eyebrow>
            <h2 className="font-display font-semibold text-ink-900 text-h2 tracking-[-0.028em] leading-[1.05] text-balance">
              QurTag works with any QR.
            </h2>
            <p className="text-body text-ink-700 text-pretty max-w-2xl">
              Got a sticker sheet from somewhere else? An old keychain? An NFC card you already
              own? Paste a QurTag URL on it and the app handles the rest. We charge for materials,
              not for software.
            </p>
            <Link to="/how-it-works" className="link-arrow text-body mt-2">
              See how it works
              <ArrowRight size={16} strokeWidth={1.75} />
            </Link>
          </div>
        </Container>
      </section>

      {/* Bulk + B2B */}
      <section className="border-t border-hairline">
        <Container size="xl">
          <div className="py-cairn-12 md:py-cairn-8 grid lg:grid-cols-2 gap-cairn-8">
            <div className="rounded-modal border border-hairline bg-canvas p-cairn-5 flex flex-col gap-3">
              <Package size={22} strokeWidth={1.25} className="text-verdigris-700" />
              <Eyebrow>Bulk packs</Eyebrow>
              <h3 className="font-display font-semibold text-h4 text-ink-900 tracking-[-0.018em] text-balance">
                For the whole household, or the whole team.
              </h3>
              <p className="text-body text-ink-700 text-pretty">
                Stickers come in 5-pack, 12-pack, and 40-pack tiers. Scan one to activate the
                whole pack at once. The app names them, assigns them, generates labels.
              </p>
              <Link to="/start" className="link-arrow text-caption text-ink-900 mt-2">
                Start a pack →
              </Link>
            </div>
            <div className="rounded-modal border border-hairline bg-canvas p-cairn-5 flex flex-col gap-3">
              <Printer size={22} strokeWidth={1.25} className="text-verdigris-700" />
              <Eyebrow>For business</Eyebrow>
              <h3 className="font-display font-semibold text-h4 text-ink-900 tracking-[-0.018em] text-balance">
                Every laptop in the building, for $4 each.
              </h3>
              <p className="text-body text-ink-700 text-pretty">
                Corporate IT, schools, sports clubs, conference centers. Volume pricing kicks in
                at 100 stickers. Custom branding on the finder page on Business tier.
              </p>
              <Link to="/business" className="link-arrow text-caption text-ink-900 mt-2">
                Talk to us →
              </Link>
            </div>
          </div>
        </Container>
      </section>

      {/* Outro */}
      <section className="border-t border-hairline">
        <Container size="md">
          <div className="py-cairn-8 flex flex-col items-start gap-6">
            <h2 className="font-display font-semibold text-ink-900 text-h1 tracking-[-0.038em] leading-[0.95] text-balance">
              Start with a sticker. Upgrade when you fall for it.
            </h2>
            <div className="flex items-center gap-6">
              <Link
                to="/start"
                className="inline-flex h-12 items-center gap-2 rounded-pill bg-ink-900 px-6 text-body font-medium text-canvas hover:bg-ink-700 transition-colors duration-cairn"
              >
                Start free
                <ArrowRight size={16} strokeWidth={1.75} />
              </Link>
              <Link to="/pricing" className="link-arrow text-body">
                See pricing
                <ArrowRight size={16} strokeWidth={1.75} />
              </Link>
            </div>
          </div>
        </Container>
      </section>
    </>
  );
}
